name: mayo
description: A Muay Thai Gym membership and reservation app.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.2
    firebase_core: ^1.18.0
    firebase_auth: ^3.3.20
    intl: ^0.17.0
    google_fonts: ^3.0.1
    mask_text_input_formatter: ^2.3.0
    flutter_riverpod: ^1.0.4
    cloud_firestore: ^3.2.1
    shared_preferences: ^2.0.15
    image_picker: ^0.8.5+3
    firebase_storage: ^10.3.1
    http: ^0.13.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    generate: true

    assets:
        - ./assets/icons/
        - ./assets/texts/
