// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmB8-tBKD2nOBDbBfz-8TGcsOJEc7GtPM',
    appId: '1:874486023489:web:b8765f7595b771e0408dc0',
    messagingSenderId: '874486023489',
    projectId: 'mayo-muaythai',
    authDomain: 'mayo-muaythai.firebaseapp.com',
    storageBucket: 'mayo-muaythai.appspot.com',
    measurementId: 'G-KXGL1N9L88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSn-cKhT4uaJGf4Yf33QoPcbes2mQ3-U',
    appId: '1:874486023489:android:75e82706c445eb53408dc0',
    messagingSenderId: '874486023489',
    projectId: 'mayo-muaythai',
    storageBucket: 'mayo-muaythai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbw9g1ztfHi0UotIBwoYwrd3rkGHDlPNc',
    appId: '1:874486023489:ios:a7f965548d5ef6fb408dc0',
    messagingSenderId: '874486023489',
    projectId: 'mayo-muaythai',
    storageBucket: 'mayo-muaythai.appspot.com',
    iosClientId: '874486023489-5l66u3bebd59iejiruhtgcvv1p1lgouc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mayo',
  );
}
